InoxPhuocThanh/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InoxPhuocThanh.Models
{
    public class ContactViewModel
    {
        public int Contact_id { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Vui lòng nhập họ và tên")]
        [Display(Name = "Họ và tên")]
        public string Fullname { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại")]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Số điện thoại")]
        public string PhoneNumber { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Vui lòng nhập chủ đề")]
        [Display(Name = "Chủ đề")]
        public string Title { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Yêu cầu")]
        public string Description { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage = "Vui lòng nhập mail")]
        [EmailAddress]
        [Display(Name ="Email")]
        public string Customer_email { get; set; }
        public DateTime Created_date { get; set; }
    }
}

InoxPhuocThanh/Controllers/ContactController.cs
 using AutoMapper;
using InoxPhuocThanh.Models;
using InoxPhuocThanh.Service.Interface;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.IO;
using System.Linq;

namespace InoxPhuocThanh.Controllers
{
    public class ContactController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        public ContactController(ICompanyService companyService, IMapper mapper)
        {
            this._companyService = companyService;
            this._mapper = mapper;
        }
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CompanyInfoPartial()
        {
            List<CompanyViewModel> model;
            model = _mapper.Map<List<CompanyViewModel>>(_companyService.GetCompanyInformation());
            return PartialView("_PartialInforContact", model);
        }


        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Index(ContactViewModel contact)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var mail = new SmtpClient("smtp.gmail.com", 25)
                    {
                        Credentials = new NetworkCredential("tramanhc9p@gmail.com", "fantramanh"),
                        EnableSsl = true
                    };
                    var message = new MailMessage();
                    message.From = new MailAddress("tramanhc9p@gmail.com");
                    message.ReplyToList.Add("tramanhc9p@gmail.com");
                    message.To.Add("congson1603@gmail.com");
                    message.Subject = contact.Title;
                    message.IsBodyHtml = true;
                    string htmlString = @"<html>" +
                          "<body>" +
                          "<p>Xin chào! Xưởng Inox Phước Thành,</p>" +
                          "<p>Tôi tên là: " + contact.Fullname + "</p>" +
                          "<p>Email: " + contact.Customer_email + "</p>" +
                          "<p>Số điện thoại: " + contact.PhoneNumber + "</p>" +
                          "<p>Nội dung: " + contact.Description + "</p>" +
                          "<p>Xin cảm ơn</p>" +
                          "<p>Khách hàng</p>" +
                          "</body>" +
                          "</html>";
                    message.Body = htmlString;
                    HttpFileCollectionBase files = Request.Files;
                    HttpPostedFileBase file;
                    string fname;
                    for (int i = 0; i < files.Count; i++)
                    {
                        file = files[i];
                        fname = file.FileName;
                        fname = Path.Combine(Server.MapPath("~/img/contact/"), fname);
                        file.SaveAs(fname);
                        message.Attachments.Add(new Attachment(file.InputStream, fname));
                    }
                    mail.Send(message);

                }
                catch (Exception ex)
                {
                    return Json(ex.Message + " Files failed");
                }
            }
            return View();
        }


    }
}

InoxPhuocThanh/Views/Contact/Index.cshtml
@model InoxPhuocThanh.Models.ContactViewModel
@{
    ViewBag.Title = "Liên Hệ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .mapouter {
        position: relative;
        text-align: right;
        height: 450px;
        width: 100%;
    }

    .gmap_canvas {
        overflow: hidden;
        background: none !important;
        height: 450px;
        width: 100%;
    }

    .contact-map {
    }
</style>
<!-- Breadcurb AREA -->
<div class="breadcurb-area">
    <div class="container">
        <ul class="breadcrumb">
            <li>@Html.ActionLink("Trang Chủ", "Index", "Home")</li>
            <li>Liên Hệ</li>
        </ul>
    </div>
</div>
<!-- Contact-us area -->
<div class="contact-us-area">
    <div class="map-area">
        <div class="contact-map">
            <div class="mapouter">
                <div class="gmap_canvas"><iframe width="100%" height="450" id="gmap_canvas" src="https://maps.google.com/maps?q=312A%20T%C3%A2n%20K%E1%BB%B3%20T%C3%A2n%20Qu%C3%BD&t=k&z=17&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://www.embedgooglemap.net"></a></div>
            </div>
        </div>
    </div>
    <div class="contact-information">
        <div class="container">
            <div class="row">
                @Html.Action("CompanyInfoPartial", "Contact")
                <div class="col-md-6 col-sm-6">
                    <div class="contact-leave-message">
                        <div class="contact-head">
                            <h2>Liên hệ mua sỉ</h2>
                        </div>
                        @using (Html.BeginForm("Index", "Contact", FormMethod.Post, new { enctype="multipart/form-data"}))
                        {
                            @Html.AntiForgeryToken()
                            HtmlHelper.UnobtrusiveJavaScriptEnabled = false;

                            <div class="form-horizontal">
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group col-md-6">
                                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

                                </div>

                                <div class="form-group col-md-6">
                                    @Html.LabelFor(model => model.Fullname, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.Fullname, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Fullname, "", new { @class = "text-danger" })

                                </div>

                                <div class="form-group col-md-6">
                                    @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })

                                </div>
                                <div class="form-group col-md-6">
                                    @Html.LabelFor(model => model.Customer_email, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.Customer_email, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Customer_email, "", new { @class = "text-danger" })

                                </div>
                                <div class="form-group col-md-12">
                                    <label class="control-label">
                                        Thêm hình ảnh
                                    </label>
                                    <input type="file" multiple name="file" accept="image/*" class="form-control">
                                </div>
                                <div class="form-group col-md-12">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

                                </div>



                                <div class="form-group col-md-12">
                                    <input type="submit" id="btnSendMail" value="Gửi" class="btn btn-default" />
                                </div>
                            </div>
                        }


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
      function preview_image() {
          var total_file = document.getElementById("fileupload").files;
          for (var i = 0; i < total_file.length; i++)
         {
              //$('#image_preview').append("<img src='"+URL.createObjectURL(event.target.files[i])+"'><br>");
              $('#image_preview').append("<p id="+i+"> " + total_file[i].name + "&nbsp<a><i class='fa fa-remove' onclick=delete_image('" + total_file[i].name + "')></i></a>" + "</p>");
         }
      }
      function delete_image(imgname) {
          var total_file = document.getElementById("fileupload").files;
          for (var i = 0; i < total_file.length; i++)
          {
              if (total_file[i].name == imgname) {
                  total_file[i];

                  }
         }
      }
    @*$(function () {
        var sendMail = $('#btnSendMail');
                var formData = new FormData();
        $('#fileupload').on("change", function () {
            preview_image();
                var files = $("#fileupload").get(0).files;
                for (i = 0; i < files.length; i++) {
                    formData.append(files[i].name, files[i]);
                }
            })
        sendMail.on('click', function () {

        formData.append('fullname', $("#fullname").val());
        formData.append('title', $("#title").val());
        formData.append('phonenumber', $("#phonenumber").val());
        formData.append('description', $("#description").val());
        formData.append('email', $("#email").val());
        $.ajax({
            type: "POST",
            url: "@Url.Action("Index")",
            data: formData,
            contentType: false,
            processData: false,
            success: function (data) {
                alert("success");
            },
            error: function (data) {
                alert("error: " + data.statusText);
            }

        })
        });
    });*@
</script>

<style>
    .field-validation-error {
        color: red;
        font-weight: bold;
    }
</style>

InoxPhuocThanh/Views/Contact/_PartialInforContact.cshtml
<div class="col-md-6 col-sm-6">
    <div class="contact-details">
        <div class="contact-head">
            <h2>Thông tin liên hệ</h2>
            <p>@Model[0].Company_description</p>
        </div>
        <div class="contact-bottom">
            <p><span><i class="fa fa-phone"></i></span> Sdt: @Model[0].Company_phonenumber1 - @Model[0].Company_phonenumber2</p>
            <p><span><i class="fa fa-envelope"></i></span> E-mail: @Model[0].Company_gmail</p>
            <p>
                <span><i class="fa fa-link"></i></span> Website: <a href="inoxphuocthanh.com">inoxphuocthanh.com</a>
            </p>
            <p><span><i class="fa fa-map-marker"></i></span> Address: @Model[0].Company_address</p>
        </div>
        <div class="contact-social-icon footer-social-icon">
            <ul class="list-inline">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
        </div>
    </div>
</div>