InoxPhuocThanh/Areas/AdminPT/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InoxPhuocThanh.Areas.AdminPT.Models
{
    public class ProductViewModel
    {
        public int Product_id { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn danh mục")]
        [Display(Name = "Danh mục sản phẩm")]
        public int Product_category_id { get; set; }
        public string Category_name { get; set; }

        public int Product_type_id { get; set; }
      
        public string Product_type_name { get; set; }

        [StringLength(100)]
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        [Display(Name = "Tên sản phẩm")]
        public string Product_name { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập giá sản phẩm")]
        [Display(Name = "Giá sản phẩm")]
        public float Product_price { get; set; }
        //[StringLength(50)]
        //[Required(ErrorMessage = "Vui lòng thêm hình ảnh sản phẩm")]
        //[Display(Name = "Hình sản phẩm")]
        public string Product_image { get; set; }
        public DateTime Product_created_date { get; set; }
        [StringLength(200)]
        [Required(ErrorMessage = "Vui lòng thêm chi tiết sản phẩm")]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Chi tiết")]
        public string Product_description { get; set; }
        [Required(ErrorMessage = "Vui lòng thêm số lượng")]
        [Display(Name = "Số lượng")]
        public int Product_quantity { get; set; }
        public bool IsDelete { get; set; }
        public bool IsActive { get; set; }
        public int CountNum { get; set; }
        public string Price { get; set; }

    }
}

InoxPhuocThanh/Models/ProductViewModel.cs
using System;

namespace InoxPhuocThanh.Models
{
    public class ProductViewModel
    {
        public int Product_id { get; set; }
        public int Product_category_id { get; set; }
        public int Product_type_id { get; set; }
        public string Product_name { get; set; }
        public float Product_price { get; set; }
        public string Product_image { get; set; }
        public DateTime Product_created_date { get; set; }
        public string Product_description { get; set; }
        public int Product_quantity { get; set; }
        public bool IsDelete { get; set; }
        public bool IsActive { get; set; }
        public int CountNum { get; set; }
        public string Price { get; set; }
        public double PageNumber { get; set; }

    }
}

InoxPhuocThanh/Areas/AdminPT/Controllers/ProductController.cs
using Dapper;
using InoxPhuocThanh.Areas.AdminPT.Implement;
using InoxPhuocThanh.Areas.AdminPT.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InoxPhuocThanh.Areas.AdminPT.Controllers
{
    public class ProductController : Controller
    {
        // GET: AdminPT/Product
        public ActionResult Index()
        {
            using (var connection = ConnectionProvider.Get())
            {
                var model = connection.QueryMultiple("sp_admin_getListProduct", commandType: CommandType.StoredProcedure);
                var product = model.Read<ProductViewModel>().ToList();
                var cate = connection.QueryMultiple("sp_admin_getListCategory", commandType: CommandType.StoredProcedure);
                var categories = cate.Read<CategoryViewModel>().Where(x => x.IsActive == true).ToList();
                var proType = connection.QueryMultiple("sp_admin_getProductType", commandType: CommandType.StoredProcedure);
                var productTypes = proType.Read<ProductTypeViewModel>().ToList();
                ViewData["categories"] = categories;
                ViewData["productTypes"] = productTypes;
                return View(product);
            }
        }
        public ActionResult Insert()
        {
            using (var connection = ConnectionProvider.Get())
            {
                var cate = connection.QueryMultiple("sp_admin_getListCategory", commandType: CommandType.StoredProcedure);
                var categories = cate.Read<CategoryViewModel>().Where(x => x.IsActive == true).ToList();
                var proType = connection.QueryMultiple("sp_admin_getProductType", commandType: CommandType.StoredProcedure);
                var productTypes = proType.Read<ProductTypeViewModel>().ToList();
                ViewData["categories"] = categories;
                ViewData["productTypes"] = productTypes;
                return View();
            }
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Insert(ProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                using (var connection = ConnectionProvider.Get())
                {
                    var IsSucess = connection.Execute("sp_admin_InsertProduct", new
                    {
                        model.Product_category_id,
                        model.Product_type_id,
                        model.Product_name,
                        model.Product_price,
                        model.Product_quantity,
                        model.Product_image,
                        model.Product_description,
                        model.IsActive

                    }, commandType: CommandType.StoredProcedure) > 0;
                }
                return RedirectToAction("Index", "Product");
            }
            using (var connection = ConnectionProvider.Get())
            {
                var cate = connection.QueryMultiple("sp_admin_getListCategory", commandType: CommandType.StoredProcedure);
                var categories = cate.Read<CategoryViewModel>().Where(x => x.IsActive == true).ToList();
                var proType = connection.QueryMultiple("sp_admin_getProductType", commandType: CommandType.StoredProcedure);
                var productTypes = proType.Read<ProductTypeViewModel>().ToList();
                ViewData["categories"] = categories;
                ViewData["productTypes"] = productTypes;
                return View(model);
            }
        }
        public ActionResult DeleteProduct(int Id)
        {
            var IsSucess = false;
            using (var connection = ConnectionProvider.Get()) {
                 IsSucess = connection.Execute("sp_admin_deleteProduct", new
                {
                    Id
                }, commandType: CommandType.StoredProcedure) >0;
            }
            return Json(new { success = IsSucess }, JsonRequestBehavior.AllowGet);
        }
    }
}

InoxPhuocThanh/Controllers/CategoryController.cs
using AutoMapper;
using InoxPhuocThanh.Models;
using InoxPhuocThanh.service.Interface;
using InoxPhuocThanh.Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InoxPhuocThanh.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        public CategoryController(ICategoryService categoryService,IProductService productService, IMapper mapper)
        {
            this._categoryService = categoryService;
            this._productService = productService;
            this._mapper = mapper;
        }
        // GET: Category
        public ActionResult CategoryPartial()
        {
            List<CategoryViewModel> category;
            category = _mapper.Map<List<CategoryViewModel>>(_categoryService.GetCategories());
            return PartialView("_CategoryPartial", category);
        }

        public ActionResult CategorySearchPartial()
        {
            List<CategoryViewModel> category;
            category = _mapper.Map<List<CategoryViewModel>>(_categoryService.GetCategories());
            return PartialView("_CategorySearch_Partial", category);
        }

        public ActionResult GetProductByCategoryName(int category, int type, int pageNum = 1)
        {
            int pageSize = 2;
            if (category.ToString() == null)
            {
                Session.Add("name", type);
            }
           
            if (pageNum.ToString() == null)
            {
                pageNum = 1;
            }
            List<ProductViewModel> model;
            model = _mapper.Map<List<ProductViewModel>>(_productService.GetListProductByCategoryName("sss", pageSize, pageNum));
            return View("../Product/Index", model);
        }
        public ActionResult GetProductByTypeName(string name, int pageNum = 1)
        {
            int pageSize = 2;
            //var nameSession = (string)Session["name"];
            if (name == null)
            {
                name = "";
            }
            if (name != null)
            {
                Session.Add("name", name);
            }
            if (pageNum.ToString() == null)
            {
                pageNum = 1;
            }
            List<ProductViewModel> model;
            model = _mapper.Map<List<ProductViewModel>>(_productService.GetListProductByTypeName(name, pageSize, pageNum));
            return View("../Product/Index", model);
        }
       
     
    }
}

InoxPhuocThanh/Controllers/ProductController.cs
using AutoMapper;
using InoxPhuocThanh.Models;
using InoxPhuocThanh.Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InoxPhuocThanh.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        public ProductController(IProductService productService, IMapper mapper)
        {
            this._productService = productService;
            this._mapper = mapper;
        }
        // GET: Product
        public ActionResult Index(string searchValue = "", int category = 0, int type = 0, int pageNum = 1)
        {
            int pageSize = 2;
            Session.Add("name", searchValue);
                Session.Add("type", type);
                Session.Add("category", category);
            if (pageNum.ToString() == null)
            {
                pageNum = 1;
            }
            List<ProductViewModel> model;
            model = _mapper.Map<List<ProductViewModel>>(_productService.GetListProductByCategoryOrTypeName(searchValue, category, type, pageSize, pageNum));
            foreach(ProductViewModel product in model)
                product.Price = product.Product_price.ToString("N0");
            if(model[0].CountNum % pageSize == 0)
            {
                model[0].PageNumber = model[0].CountNum / pageSize;
            } else
            {
                model[0].PageNumber = 1.0 * Convert.ToDouble(model[0].CountNum) / Convert.ToDouble(pageSize);
                if((model[0].PageNumber * 10) % 10 > 0)
                {
                    model[0].PageNumber = Convert.ToInt32(model[0].PageNumber) + 1;
                }else
                {
                    model[0].PageNumber = model[0].PageNumber;
                }
            }
            return View(model);
        }
        public PartialViewResult SearchProduct(string searchValue, int categorySearch = 1, int pageNum = 1)
        {
            int pageSize = 2;
            if (searchValue == null)
            {
                searchValue = "";
            }
            Session.Add("categorySearch", categorySearch);
            Session.Add("name", searchValue);
            List<ProductViewModel> model;
            model = _mapper.Map<List<ProductViewModel>>(_productService.SearchProduct(searchValue, categorySearch, pageSize, pageNum));
            foreach (ProductViewModel product in model)
                product.Price = product.Product_price.ToString("N0");
            return PartialView("Index",model);
        }
    }
}

InoxPhuocThanh/Controllers/ProductDetailController.cs
using AutoMapper;
using InoxPhuocThanh.Models;
using InoxPhuocThanh.Service.Interface;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InoxPhuocThanh.Controllers
{
    public class ProductDetailController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;
        public ProductDetailController(IProductService productService, IMapper mapper)
        {
            this._productService = productService;
            this._mapper = mapper;
        }
        // GET: ProductDetail
        public ActionResult Index(int id)
        {
            if (id.ToString()==null)
            {
                id = 0;
            }
            ProductViewModel model;
            model = _mapper.Map<ProductViewModel>(_productService.GetProductDetail(id));
            model.Price = model.Product_price.ToString("N0");
            return View(model);
        }
    }
}

InoxPhuocThanh/Views/Product/Index.cshtml
@model List<InoxPhuocThanh.Models.ProductViewModel>
@{
    ViewBag.Title = "Sỉ lẻ";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="productpage">
    <div class="breadcurb-area">
        <div class="container">
            <ul class="breadcrumb">
                <li>@Html.ActionLink("Trang Chủ", "Index", "Home")</li>
                <li>Bán sỉ & lẻ</li>
            </ul>
        </div>
    </div>
    <!-- Product Item AREA -->
    <div class="product-item-area">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-4">
                    <div class="product-type">
                        @Html.Action("CategoryPartial", "Category")
                    </div>
                </div>
                <div class="col-md-9 col-sm-8">
                    <div class="product-item-list">
                        <div class="row">
                            <div class="col-md-12 col-sm-12">
                                <div class="product-item-heading">
                                    <div class="item-heading-title">
                                        <h2>Bàn ghế</h2>
                                    </div>
                                    <div class="result-short-view">
                                        <div class="result-short">
                                            <p>Có @Model.Count kết quả được tìm thấy </p>
                                            <div class="result-short-selection">
                                                <select>
                                                    <option>Mặc định</option>
                                                    <option>Sắp xếp theo lượt yêu thích</option>
                                                    <option>Sắp xếp theo đánh giá</option>
                                                    <option>Sắp xếp theo sản phẩm mới</option>
                                                    <option>Sắp xếp giá từ thấp lên cao</option>
                                                    <option>Sắp xếp giá từ cao xuống thấp</option>
                                                </select>
                                                <i class="fa fa-sort-alpha-asc"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            @for (int i =0; i < Model.Count; i++)
                            {
                                <div class="col-md-4 col-sm-6">
                                    <div class="single-item-area">
                                        <div class="single-item">
                                            <div class="product-item-img">
                                                <a href="#">
                                                    <img class="primary-img" src="~/img/shop/Single-product-3.jpg" alt="item">
                                                    <img class="secondary-img" src="~/img/shop/Single-product-3.jpg" alt="item">
                                                </a>
                                                <div class="product-item-action">
                                                    <a><i class="fa fa-external-link"></i></a>
                                                    <a href="#"><i class="fa fa-shopping-cart"></i></a>
                                                </div>
                                            </div>
                                            <div class="single-item-content">
                                                <h2><a href="#">@Model[i].Product_name</a></h2>
                                                <div class="best-product-rating">
                                                    <a href="#"><i class="fa fa-star"></i></a>
                                                    <a href="#"><i class="fa fa-star"></i></a>
                                                    <a href="#"><i class="fa fa-star"></i></a>
                                                    <a href="#"><i class="fa fa-star"></i></a>
                                                    <a href="#"><i class="fa fa-star"></i></a>
                                                </div>
                                                <h3>Giá :@Model[i].Price</h3>
                                            </div>
                                        </div>
                                        <div class="item-action-button fix">
                                            <a href="#">Thêm giỏ hàng</a>
                                            <div class="item-action-icon">
                                                <a href="#"><i class="fa fa-heart"></i></a>
                                                <a href="#"><i class="fa fa-signal"></i></a>
                                                <a href="@Url.Action("Index","ProductDetail",new { id = @Model[i].Product_id})"><i class="fa fa-search"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                    <div class="shop-pagination floatright">
                        <ul class="pagination">
                            @for (int i = 1; i <= @Model[0].PageNumber; i++)
                            {
                                <li><a href="@Url.Action("Index", "Product", new {searchValue = (string)Session["name"], category = (int)Session["category"] ,type = (int)Session["type"], pageNum = @i})">@i</a></li>
                            }

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>