InoxPhuocThanh/Models/BlogViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InoxPhuocThanh.Models
{
    public class BlogViewModel
    {
        public int Blog_id { get; set; }
        public string Blog_name { get; set; }
        public string Blog_description { get; set; }
        public string Blog_summary { get; set; }
        public DateTime Blog_created_date { get; set; }
        public string Blog_author { get; set; }
        public string Blog_img { get; set; }
        public int CountNum { get; set; }
        public double PageNumber { get; set; }
    }
}

InoxPhuocThanh/Controllers/BlogController.cs
using AutoMapper;
using InoxPhuocThanh.Models;
using InoxPhuocThanh.service.Interface;
using InoxPhuocThanh.Service.Interface;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace InoxPhuocThanh.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService;
        private readonly IMapper _mapper;
        public BlogController(IBlogService blogService, IMapper mapper)
        {
            this._blogService = blogService;
            this._mapper = mapper;
        }
        // GET: Blog
        public ActionResult Index(int Id = 0, int pageSize = 2, int pageNum = 0)
        {
            if(pageNum == 0)
            {
                pageNum = 1;
            }
            var model = _mapper.Map<List<BlogViewModel>>(_blogService.getBlogById(Id, pageSize, pageNum));
            if (model[0].CountNum % pageSize == 0)
            {
                model[0].PageNumber = model[0].CountNum / pageSize;
            }
            else
            {
                model[0].PageNumber = 1.0 * Convert.ToDouble(model[0].CountNum) / Convert.ToDouble(pageSize);
                if ((model[0].PageNumber * 10) % 10 > 0)
                {
                    model[0].PageNumber = Convert.ToInt32(model[0].PageNumber)+1;
                }
                else
                {
                    model[0].PageNumber = model[0].PageNumber;
                }
            }
            return View(model);
        }

        public PartialViewResult BlogPartial()
        {
            var model = _mapper.Map<List<BlogViewModel>>(_blogService.getListBlog());
            return PartialView("NewBlogPartial",model);
        }
    }
}

InoxPhuocThanh/Views/Blog/Index.cshtml
@model List<InoxPhuocThanh.Models.BlogViewModel>
@{
    ViewBag.Title = "Cẩm nang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- HEADER AREA -->
<div class="breadcurb-area">
    <div class="container">
        <ul class="breadcrumb">
            <li>@Html.ActionLink("Trang Chủ", "Index", "Home")</li>
            <li>@Html.ActionLink("Cẩm nang","Index/0", "Blog")</li>
        </ul>
    </div>
</div>
<!-- Product Item AREA -->
<div class="Single-blog-area">
    <div class="container">
        <div class="row">
            <div class="col-md-9 col-sm-8">

                <div class="single-blog-post-area fix">

                    <div class="single-blog-post fix">
                        @foreach (var blog in Model)
                        {
                            <div class="blog-img single-add">
                                <a href="#"><img src="~/img/blog/single-blog/b-head.jpg" alt="blog"></a>
                            </div>
                            <div class="single-blog-content fix">
                                <div class="blog-heading-title fix">
                                    <h1>@blog.Blog_name </h1>
                                    <p>Đăng bởi: <a href="#">@blog.Blog_author</a> </p>
                                    <p><i class="fa fa-clock-o"></i>@blog.Blog_created_date</p>
                                </div>
                                <div class="blog-main-content fix">
                                    <p>
                                        @blog.Blog_description
                                    </p>
                                </div>
                            </div>
                            <div class="single-blog-bottom-content">
                                <p>
                                    @blog.Blog_summary
                                </p>
                            </div>
                            <div class="social-share-icon">
                                <p>Chia sẻ</p>
                                <ul class="list-inline">
                                    <li><a target='_blank' href='http://www.facebook.com/share.php?u=https://www.google.com/' title='Chia sẽ lên Facebook'><img src='~/img/social-1.jpg' /></a></li>
                                </ul>
                            </div>
                        }



                    </div>

                </div>
                <div class="single-blog-pagination shop-pagination">
                    <ul class="pagination">
                        @for (int i = 1; i <= @Model[0].PageNumber; i++)
                        {
                            <li><a href="@Url.Action("Index", "Blog", new {pageNum = @i})">@i</a></li>
                        }

                    </ul>
                </div>
            </div>
            @Html.Action("BlogPartial", "Blog")
        </div>
    </div>
</div>

InoxPhuocThanh/Views/Blog/NewBlogPartial.cshtml
@model List<InoxPhuocThanh.Models.BlogViewModel>
<div class="col-md-3 col-sm-4">

    <div class="feature-post right-post-area">
        <div class="single-right-post">
            <div class="post-head">
                <h2>Tin mới</h2>
            </div>
            @foreach (var mode in Model)
            {
                <div class="post-img-content">
                    <div class="post-img single-add">
                        <a href="#"><img src="~/img/blog/f1.jpg" alt="post"></a>
                        @*<a href="#"><img src="img/blog/@mode.Product_image" alt="post"></a>*@
                    </div>
                    <div style="text-align:left">
                        <b class="col-md-12"><a style="color:#2B82AD;" href="@Url.Action("Index","Blog",new { Id = mode.Blog_id})"> @mode.Blog_name</a></b>
                        <b class="col-md-12" style="text-align: right">@mode.Blog_created_date.ToString("MM/dd/yyyy H:mm")</b>
                    </div>
                    <br />
                    <br />
                </div>
            }
        </div>
    </div>
</div>